/*
Name : Roger Ojar
ID : 809000518
Assignment 1
 */


package cardcounterudpclient;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.*;
import java.net.*;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Iterator;
import javax.imageio.ImageIO;
import javax.imageio.ImageReadParam;
import javax.imageio.ImageReader;
import javax.imageio.stream.ImageInputStream;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
/**
 *
 * @author Roger
 */
public class cardCounterUDPClientForm extends javax.swing.JFrame {

    /**
     * Creates new form cardCounterUDPClientForm
     */
    ArrayList<String> numberList = new ArrayList<String>();
    ArrayList<String> suitList = new ArrayList<String>(); 
    DatagramSocket aSocket = null;
    String addressName = "localhost";
    int countSpecial = 0;
    
    public cardCounterUDPClientForm() {
        initComponents();
        loadCombos();
        doSpeical("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jTextField1.setEditable(false);

        jButton1.setText("Send");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Card Counter Program");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel2.setText("Choose a card value :");

        jLabel3.setText("Choose a card suit :");

        jButton2.setText("Special");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setText("Card log :");

        jButton3.setText("Quit");
        jButton3.setEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(104, 104, 104)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(28, 28, 28)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
		try {
            byte [] m = null;   
			aSocket = new DatagramSocket();    
			InetAddress aHost = InetAddress.getByName(addressName);
			int serverPort = 6789;
            String s1 = String.valueOf(jTextField1.getText()); 
			m = s1.getBytes();                                           
			DatagramPacket request =
			new DatagramPacket(m,  s1.length(), aHost, serverPort);
			aSocket.send(request);			                        
            jButton3.setEnabled(true);
            countSpecial++;
            if(countSpecial >= 5){
            	jButton2.setEnabled(true);
            }
            jTextArea1.append(String.valueOf(jComboBox1.getSelectedItem()) + " of " + String.valueOf(jComboBox2.getSelectedItem()) + " Sent to Server\n");
		}catch (SocketException e){System.out.println("Socket: " + e.getMessage());
		}catch (IOException e){System.out.println("IO: " + e.getMessage());
		}    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            // TODO add your handling code here:
             doSpeical("SPECIAL");
             jTextArea1.append("SPECIAL Sent to Server\n");
    }//GEN-LAST:event_jButton2ActionPerformed
    
    private void doSpeical(String spec){
    	 new Thread() {
            public void run() {
                try {
					if(spec == "SPECIAL"){
						byte [] m = null;   
						aSocket = new DatagramSocket();    
						InetAddress aHost = InetAddress.getByName(addressName);
						int serverPort = 6789; 
			            String s1 = spec; 
						m = s1.getBytes();                                           
						DatagramPacket request =
						new DatagramPacket(m,  s1.length(), aHost, serverPort);
						aSocket.send(request);			                        
						byte[] buffer = new byte[100000];
						DatagramPacket reply = new DatagramPacket(buffer, buffer.length);	
						aSocket.receive(reply);
						jTextArea1.append("Total amount of cards previously sent to Server = " + new String(reply.getData()));		
					}     
				}catch (SocketException e){System.out.println("Socket: " + e.getMessage());
				}catch (IOException e){System.out.println("IO: " + e.getMessage());
				}catch (Exception e){
		                 e.printStackTrace();
		                 System.exit(1);
            	} 
            }
        }.start(); 
    }

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        String x = String.valueOf(jComboBox1.getSelectedItem());
        String y = String.valueOf(jComboBox2.getSelectedItem());
        
        
        if(x == "Ace"){
            x = "A";
        }else if(x == "King"){
            x = "K";
        }else if(x == "Queen"){
            x = "Q";
        }else if(x == "Jack"){
            x = "J";
        }
        
        if(y == "Hearts"){
            y = "H";
        }else if(y == "Clubs"){
            y = "C";
        }else if(y == "Spades"){
            y = "S";
        }else if(y == "Diamonds"){
            y = "D";
        }
        
        if(x != "Please select a value" && y != "Please select a value"){
            jTextField1.setText(x + y);
            jButton1.setEnabled(true);
        }else{
            jTextField1.setText("");
            jButton1.setEnabled(false);
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        String x = String.valueOf(jComboBox1.getSelectedItem());
        String y = String.valueOf(jComboBox2.getSelectedItem());
        
        //do conditions
        
        if(x == "Ace"){
            x = "A";
        }else if(x == "King"){
            x = "K";
        }else if(x == "Queen"){
            x = "Q";
        }else if(x == "Jack"){
            x = "J";
        }
        
        if(y == "Hearts"){
            y = "H";
        }else if(y == "Clubs"){
            y = "C";
        }else if(y == "Spades"){
            y = "S";
        }else if(y == "Diamonds"){
            y = "D";
        }
        
         if(x != "Please select a value" && y != "Please select a value"){
            jTextField1.setText(x + y);
            jButton1.setEnabled(true);
        }else{
            jTextField1.setText("");
            jButton1.setEnabled(false);
        }
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {
            byte [] m = null;   
			aSocket = new DatagramSocket();    
			InetAddress aHost = InetAddress.getByName(addressName);
			int serverPort = 6789;
            String s1 = "QUIT"; 
			m = s1.getBytes();                                           
			DatagramPacket request =
			new DatagramPacket(m,  s1.length(), aHost, serverPort);
			aSocket.send(request);			                        
			jTextArea1.append("QUIT Sent to Server\n");
		}catch (SocketException e){System.out.println("Socket: " + e.getMessage());
		}catch (IOException e){System.out.println("IO: " + e.getMessage());
		}
    }//GEN-LAST:event_jButton3ActionPerformed

    private void loadCombos(){
          numberList.add("Please select a value"); 
          numberList.add("2");    
          numberList.add("3");    
          numberList.add("4");   
          numberList.add("5");  
          numberList.add("6");
          numberList.add("7");
          numberList.add("8");
          numberList.add("9");
          numberList.add("10");
          numberList.add("Jack");
          numberList.add("Queen");
          numberList.add("King");
          numberList.add("Ace");
          
          suitList.add("Please select a value");
          suitList.add("Hearts");
          suitList.add("Diamonds");
          suitList.add("Clubs");
          suitList.add("Spades");
          
          
          String[] array = numberList.toArray(new String[numberList.size()]);
          String[] array2 = suitList.toArray(new String[suitList.size()]);
          jComboBox1.removeAllItems();
          for(String str : array) {
            jComboBox1.addItem(str);
          }
          
          jComboBox2.removeAllItems();
          for(String str : array2) {
            jComboBox2.addItem(str);
          }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cardCounterUDPClientForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cardCounterUDPClientForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cardCounterUDPClientForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cardCounterUDPClientForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cardCounterUDPClientForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
